

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/suphub_db
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: lilipg
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 8080



